services:
  consoleapp1:
    image: consoleapp1
    build:
      context: .
      dockerfile: ConsoleApp1/Dockerfile

  phos.orchestrator.api:
    image: phos.orchestrator.api
    build:
      context: .
      dockerfile: Phos.Orchestrator.Api/Dockerfile

