FROM httpd:2.4


COPY ./dist/ /usr/local/apache2/htdocs/

# Build image with:         docker build . --tag angulon-frontend:latest
# Tag image as latest       docker tag angulon-frontend staijn/angulon-frontend:latest
# push to repository        docker push staijn/angulon-frontend:latest
